### PR TITLE
Tweak smart deselection

### PR DESCRIPTION
**Pull request by ZevEisenberg**
For reasoning, see this comment and my followup: https://www.raizlabs.com/dev/2016/05/smarter-animated-row-deselection-ios/#comment-12391

### CODE REVIEW

**Comment by dostrander** [comment]
@ZevEisenberg Looks good and makes sense. I changed up the implementation of this slightly in the #51 branch. Curious if you would give it a 👍 or 👎 . Also going to fix conflicts and merge this in once we get swift 3 in if you don't have any objections

**Comment by ZevEisenberg** [comment]
@dostrander sounds good. The use of a protocol in the new version is a nice change.

**Comment by ZevEisenberg** [comment]
@dostrander why `@nonobjc`? You could probably `@objc(rz_smoothlyDeselectItems:)`. (There would likely be a little additional churn to make sure the protocol can be used in an Obj-C context, but it might be nice to have Obj-C support.

**Comment by dostrander** [comment]
@ZevEisenberg I wouldn't be opposed, the only reason for not doing it is because it's called `Swiftilities` and seems a little odd to have objc support.  Curious the read of the room around it. If we support in 1 place we should have good support in most places

**Comment by ateliercw** [comment]
+1 for a prefixed objc version

**Comment by dostrander** [comment]
After our chats internally i am going to go with the no objc extension until necessary. @ZevEisenberg  @ateliercw

**Comment by ateliercw** [comment]
good to merge when CI completes

**Pull request merged**
