### PR TITLE
[DO NOT MERGE] Xcode 9.3 failing test case

### PR DESCRIPTION
**Pull request by chrisballinger**
I guess Circle only runs on open PRs, so I'm making this branch a PR.

Apologies for the messy diff (I generally prefer not committing the Pods folder). The meat is in `Swiftilities_AnchorageTests.swift`. In Swift 4.0 the below compiles, but does not in Swift 4.1 because the compiler is having issues understanding that `CGFloat` and `Double` are the same type, and falling back to `Any`:

screen shot 2018-03-29 at 4 09 20 pm

screen shot 2018-03-29 at 4 20 56 pm

In other cases, the shorthand enum is getting confused:

screen shot 2018-03-29 at 4 12 45 pm

The problem comes down from the fact that `adjust` is too lenient on the type constraint.

```swift
    public static func adjust<ValueType>(_ default: ValueType, for overrides: [DeviceSize: ValueType]) -> ValueType {
        return overrides[DeviceSize.current] ?? `default`
    }
```

If the code is changed to only accept CGFloats, everything works great. If I change the type constraint to `<ValueType: Numeric>` I still get the `.small` enum error. Another question is how generic do we really want this?

```swift
        // should this be allowed?
        let out = DeviceSize.adjust("cool", for: [.small: 24])
        let out2 = DeviceSize.adjust("cool", for: [.small: UIView()])
```

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
Adjust doesn't need to work with `Any`, but it should be generic over some type - the two most common cases are numbers, like in the examples here, and strings, like a short string for a smaller phone. Colors are also possible candidates for adjustment.

**Comment by chrisballinger** [comment]
The problem is that the 4.1 compiler can no longer properly infer that CGFloat and floating point literals are the "same", so the return type of DeviceSize.adjust becomes Any if you don't manually cast. This change breaks some of our existing code.

**Comment by ZevEisenberg** [comment]
I can reproduce this without importing Anchorage. Working on a minimal test case to file a Swift bug.

**Comment by chrisballinger** [comment]
Nice! Yeah it's more of a problem with generics not working well when mixing float literals and CGFloats.

**Comment by ZevEisenberg** [comment]
Filed a Swift bug: https://bugs.swift.org/browse/SR-7484

**Comment by ZevEisenberg** [comment]
Update: I don't think this should gate a release. It's a Swift bug, and you can work around it by providing type information rather than relying on type inference :sadpanda:

**Comment by chrisballinger** [comment]
Btw constraining the generic type a bit to `Numeric` fixes it, but then you're a bit more limited and it  breaks backwards compatibility.

```
// This function has been simplified beyond recognition in service of
// making a small test case, but it has a similar type signature to
// a function in a real app that does real work.
func pick<ValueType: Numeric>(default: ValueType, overrides: [String: ValueType]) -> ValueType {
    return overrides["foo"] ?? `default`
}
```

**Pull request closed without merging**
