### PR TITLE
Fixes bug where deselection was internal

### PR DESCRIPTION
**Pull request by dostrander**

### CODE REVIEW

**Comment by dostrander** [comment]
@ZevEisenberg Would you want to review this

**Comment by ZevEisenberg** [comment]
oops 😳

**Comment by ZevEisenberg** [comment]
Hang on, I didn't have to do this on Perkins, and everything works. The extension is public. Why do we need to also do it on the methods? Something about frameworks?

**Comment by dostrander** [comment]
@ZevEisenberg This is actually fine for me now too. But this was definitely an issue at one point

**Comment by ZevEisenberg** [comment]
@do want to close this? Or still thinking we need to merge it?

**Pull request closed without merging**
