### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by eliotw1**

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
#req please rename the file to CONTRIBUTING.md so that GitHub will pick it up and show it on PRs: https://github.com/blog/1184-contributing-guidelines

**Comment by ZevEisenberg** [comment]
@eliotw1 thanks for doing this! Let's wait to merge until the email address is set up.

**Comment by eliotw1** [comment]
@ZevEisenberg I've updated the name of the file and the link to the file in the README.md. Is the intro in the README appropriate?

**Comment by ZevEisenberg** [comment]
@eliotw1 yeah, looks good. I'd add a period at the end, outside the link, since it's a sentence #pp.

**Comment by ZevEisenberg** [comment]
The email address (OpenSourceCondct@raizlabs.com) is now open. This PR is cleared for merge 👍

**Pull request merged**
